// 事前に「REST Client」のvscode拡張機能入れとく

@_apiurl = http://localhost:5000/api

//*************** Hello API ***************//

###***** 取得 *****###
GET {{_apiurl}}/hello HTTP/1.1

###***** 作成 *****###
POST {{_apiurl}}/hello HTTP/1.1
content-type: application/json

{
    "text": "second Hello"
}

###***** 更新 *****###
PUT {{_apiurl}}/hello/62021713515318337ee08cc6 HTTP/1.1
content-type: application/json

{
    "text": "updated Hello"
}

###***** 削除 *****###
DELETE {{_apiurl}}/hello/62021713515318337ee08cc6 HTTP/1.1


//*************** Users API ***************//

###***** ユーザー登録 *****###
POST {{_apiurl}}/users HTTP/1.1
content-type: application/json

# {
#     "text": "second Hello"
# }

###***** ユーザーログイン *****###
POST {{_apiurl}}/users/login HTTP/1.1
content-type: application/json

# {
#     "text": "second Hello"
# }

###***** マイユーザー取得 *****###
GET {{_apiurl}}/users/me HTTP/1.1
